apiVersion: apps/v1
kind: Deployment                           
metadata:
  name: myapp-deployment         
  labels:                                  
    app: myapp
spec:
  replicas: 3                              
  selector:                                
    matchLabels:                           
      app: myapp
  template:                                
    metadata:      
    labels:                               
        app: myapp
    spec:
      containers:
      - name: myapp
        image: 35821453379.dkr.ecr.ap-south-1.amazonaws.com/my-ecr:latest
        ports:
        - containerPort: 8080
---    
apiVersion: v1
kind: Service
metadata:
  name: "webapp-myapp-svc"
spec:
  selector:                              
    app: myapp
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
